### ISSUE TITLE
lua error

### ISSUE THREAD

**Issue by ghost** [jkralicky/Custom-ULX-Commands#11]
[ERROR] addons/ulib-master/lua/ulib/shared/util.lua:267: queueFunctionCall received a bad function
1. error - [C]:-1
   1. namedQueueFunctionCall - addons/ulib-master/lua/ulib/shared/util.lua:456
   2. execString - addons/ulib-master/lua/ulib/shared/util.lua:267
      1. execFile - addons/ulib-master/lua/ulib/shared/util.lua:231
      2. fn - addons/customcommands/lua/ulx/modules/sh/cc_util.lua:354
      3. unknown - addons/ulib-master/lua/ulib/shared/hook.lua:109

**Comment by ghost** [comment]
Why did you close this

**Comment by Decicus** [comment]
As he stated [in another issue](https://github.com/jkralicky/Custom-ULX-Commands/issues/12#issuecomment-244903102), he no longer supports/maintains this addon.

**Comment by ghost** [comment]
Its a pain this addon good and now I can't use it
