### ISSUE TITLE
Watchlist Issue

### ISSUE THREAD

**Issue by SouthpawAnex** [jkralicky/Custom-ULX-Commands#26]
Hi,

For some reason, my ULX watchlist is not displaying any of the watched players in the in-game !watchlist menu.

- I have checked the /data folder, and the data is storing perfectly fine
- The in-game chat commands work perfectly fine
- I have the latest versions of ULX and ULiB
- And the menu opens as it should

It's simply just not displaying any of the information inside the in-game !watchlist menu.

The watchlist is a very useful function, so I'd greatly appreciate any help with solving this problem.

**Comment by storm37000** [comment]
get awarns from gmodstore, the watchlist will eventually overload your connection and dc you from the server every time you veiw it, once it gets well populated.  The watchlist will be removed from this once i make a fork and upload my private self optimized and fixed version that ive been using on my server.  This addon has major security and performance issues currently!

**Comment by kralicky** [comment]
@SouthpawAnex This addon is OLD. Use at your own risk. I don't play gmod anymore and haven't made changes to this in many years.
@storm37000 feel free to upload your fixed code here, I would be happy to merge any changes/fixes you have.
