### ISSUE TITLE
version.txt is out of date

### ISSUE THREAD

**Issue by Physics-Dude** [jkralicky/Custom-ULX-Commands#27]
Custom ULX Commands returns an "[ULX-Custom-Commands]: A new version is available on GitHub" due to version.txt being out of date with cl_updatecheck.lua in both versions.

version.txt reads: 1.3.19
cl_updatecheck.lua (in both category versions) expects: 4.16.19

**Comment by kralicky** [comment]
Just updated version.txt, can you confirm it works now?

**Comment by Physics-Dude** [comment]
Unfortunately it does not. There appears to be an extra LF in version.txt. I'm not sure if this is avoidable. You may be able to remove any extra LF/CR characters in this file. 

The following code passes correctly:
```lua
http.Fetch("http://raw.githubusercontent.com/cobalt77/Custom-ULX-Commands/master/version.txt", function( body, len, headers, code)
  if body == "4.16.19\n" then 
    print("its a match! (note the single Linefeed)") 
  end 
end)
```

**Comment by kralicky** [comment]
Can you check if the following code works, the solution is to trim the body text, just need to make sure this is the correct lua syntax (haven't worked on this in a long time)

```local version = "4.16.19" -- m.d.yy
http.Fetch("http://raw.githubusercontent.com/cobalt77/Custom-ULX-Commands/master/version.txt", function( body, len, headers, code)
  local nversion = body:Trim()
  if nversion != version then
    MsgC(Color(0,191,255), "[ULX-Custom-Commands]", color_white, ": A new version is available on GitHub.\n")
  end
end)
```

**Comment by Physics-Dude** [comment]
Your code works now. Nice job!
Just make sure you define the proper current "version" beforehand in both cl_updatecheck.lua files.

**Comment by kralicky** [comment]
Patched both cl_updatecheck.lua files with the new code. Thanks for helping out!
