### ISSUE TITLE
Last update error

### ISSUE THREAD

**Issue by comedinha** [jkralicky/Custom-ULX-Commands#7]
`[ERROR] addons/customcommands/lua/autorun/server/sv_dban.lua:22: attempt to index global 'ucl' (a nil value)`

Need use "ULib.ucl", only "ucl" not exist.

**Comment by kralicky** [comment]
Make a pull request and I will merge it

**Comment by GGG-KILLER** [comment]
@jkralicky  Made a pull request #9, if you'd like to merge it.

**Comment by kralicky** [comment]
Thanks
